working_directory = "/app"
pid_file = "/tmp/graphdb.pid"
stdout = "/dev/stdout"
stderr = "/dev/stderr"

[storage]
backend = "simple"
directory = "/data"

[server]
bind_address = "0.0.0.0"
port = 8080
client_dir = "/app/client/dist"
