[package]
name = "stdfunc"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
function-api = { path = "../function-api" }
rand = "0.8"
once_cell = "1.19"
uuid = { version = "1", features = ["v4"] }
