working_directory = "/home/michael/src/db/graphdb"
pid_file = "/home/michael/src/db/graphdb/target/graphdb.pid"
stdout = "/home/michael/src/db/graphdb/target/graphdb.log"
stderr = "/home/michael/src/db/graphdb/target/graphdb.err"
umask = 18         # 0o022 written in decimal
log_level = "debug"
plugin_dir = "../../lib"

[storage]
backend = "monolith"
file = "/home/michael/src/db/graphdb/target/data/graph.monolith"

[server]
bind_address = "127.0.0.1"
port = 8080
http2_only = false
tcp_nodelay = true
# worker_threads = 4
# concurrency_limit = 128
# body_limit = 1048576
#
# [server.tls]
# cert_path = "/path/to/cert.pem"
# key_path = "/path/to/key.pem"
